kind: Namespace
apiVersion: v1
metadata:
  name: ns-0

---

kind: Namespace
apiVersion: v1
metadata:
  name: physics-namespace

---

kind: Service
apiVersion: v1
metadata:
  name: retrieve-service
  namespace: physics-namespace
spec:
  selector:
    app: fw-fs
  clusterIP: None
  ports:
    - port: 6363
      targetPort: 6363
      protocol: UDP

---

kind: Service
apiVersion: v1
metadata:
  name: subset-service
  namespace: physics-namespace
spec:
  selector:
    app: fw-fs
  clusterIP: None
  ports:
    - port: 6363
      targetPort: 6363
      protocol: UDP
---

kind: Service
apiVersion: v1
metadata:
  name: service-0
  namespace: ns-0
spec:
  selector:
    app: router
  clusterIP: None
  ports:
    - port: 6363
      targetPort: 6363
      protocol: UDP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fw-fs
  namespace: physics-namespace

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fw-fs
  template:
    metadata:
      labels:
        app: fw-fs
    spec:
        nodeSelector:
          nodevm: fw-fs-node
        tolerations:
        - key: nodevm
          operator: Equal
          value: fw-fs-node
          effect: NoSchedule
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        volumes:
        - name: hugepage
          emptyDir:
            medium: HugePages
        - name: sys
          hostPath:
            path: /sys
        - name: run-ndn
          hostPath:
            path: /run/ndn
        - name: srv-ndn-fileserver
          hostPath:
            path: /srv/fs

        containers:
        - name: fw
          image: sankalpatimilsina/ndn-dpdk-apr-27:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
              add: ["SYS_ADMIN"]
              add: ["SYS_NICE"]
              add: ["IPC_LOCK"]
            privileged: true
          volumeMounts:
          - mountPath: /dev/hugepages
            name: hugepage
          - mountPath: /sys
            name: sys
          - mountPath: /run/ndn
            name: run-ndn
          - mountPath: /srv/fs
            name: srv-ndn-fileserver
          resources:
            limits:
              hugepages-1Gi: 20Gi
              memory: 4Gi
            requests:
              hugepages-1Gi: 20Gi
              memory: 4Gi

        - name: fs
          image: sankalpatimilsina/ndn-dpdk-apr-27:latest
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "ndndpdk-svc --gqlserver http://127.0.0.1:3031" ]
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
              add: ["SYS_ADMIN"]
              add: ["SYS_NICE"]
              add: ["IPC_LOCK"]
            privileged: true
          volumeMounts:
          - mountPath: /dev/hugepages
            name: hugepage
          - mountPath: /sys
            name: sys
          - mountPath: /run/ndn
            name: run-ndn
          - mountPath: /srv/fs
            name: srv-ndn-fileserver

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  namespace: ns-0

spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
        nodeSelector:
          nodevm: router-node
        tolerations:
        - key: nodevm
          operator: Equal
          value: router-node
          effect: NoSchedule
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        volumes:
        - name: hugepage
          emptyDir:
            medium: HugePages
        - name: sys
          hostPath:
            path: /sys
        - name: run-ndn
          hostPath:
            path: /run/ndn
        - name: srv-ndn-fileserver
          hostPath:
            path: /srv/fs

        containers:
        - name: router
          image: sankalpatimilsina/ndn-dpdk-apr-27:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
              add: ["SYS_ADMIN"]
              add: ["SYS_NICE"]
              add: ["IPC_LOCK"]
            privileged: true
          volumeMounts:
          - mountPath: /dev/hugepages
            name: hugepage
          - mountPath: /sys
            name: sys
          - mountPath: /run/ndn
            name: run-ndn
          - mountPath: /srv/fs
            name: srv-ndn-fileserver
          resources:
            limits:
              hugepages-1Gi: 20Gi
              memory: 4Gi
            requests:
              hugepages-1Gi: 20Gi
              memory: 4Gi
